---
author:
  - 'Mike Eldridge <diz@cpan.org>'
distribution_type: module
generated_by: 'Module::Install version 0.80'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hopkins-Plugin-RPC
no_index:
  directory:
    - inc
requires:
  Class::Accessor::Fast: 0.31
  Getopt::Attribute: 1.44
  Hopkins: 0.900
  POE::Component::Server::SOAP: 1.11
  String::Escape: 2002.001
resources:
  license: http://dev.perl.org/licenses/
version: 0.900
